### PR TITLE
Last source and font files

### PR DESCRIPTION
**Pull request by vv-monsalve**
Hi @xotypeco, this PR includes:
- [x] New source files with the version bumped to 2.000 given it will be a VF now, so it would have s `MAJOR` change category.
- [x] Build scripts with the -f flag restored to solve the Fail on 'nested components' which has been reported again. 
- [x] New font binaries produced.

Please merge them before making any new adjustment to the fonts. E.g. solving the [last reported Fail](https://github.com/xotypeco/big_shoulders/issues/35).

Thanks

### CODE REVIEW

**Comment by xotypeco** [comment]
making this note here because I keep forgetting to write it down: don't forget to specify everything needs to export with an em unit of 4000, even though Big Shoulders & Big Shoulders Stencil are drawn at 2000. 

(just in case this isn't already automated; this is the one thing I keep forgetting to do, every single time)

**Comment by vv-monsalve** [comment]
Please check the files and ensure everything is as expected

**Comment by xotypeco** [comment]
Big Shoulders and Stencil are set at 2000 UPM while Inline is 4000. do they get scaled up via script upon export? or do these files need to be manually reset to 4000?

**Comment by vv-monsalve** [comment]
> Big Shoulders and Stencil are set at 2000 UPM while Inline is 4000. do they get scaled up via script upon export? or do these files need to be manually reset to 4000?

Hi @xotypeco. Inspecting the files again (as this was solved many months ago), there is no need to increase the UPM for BigShoulders main and Stencil variants given they are already proportional with the Inline. 
The Inline variant has a 4000 UPM, but its vertical metrics are proportionally bigger than the main version, and therefore it is not being displayed smaller than the main variant. 
Increasing up the UPM (with proportional metrics) would only increase the resulting file-size.

Screen Shot 2021-05-17 at 15 38 45


Screen Shot 2021-05-17 at 15 33 25

**Comment by xotypeco** [comment]
awesome that we can omit this step. I think I remember the original worry was that asynchronous UPM would affect display of Inline next to the others. thanks for checking it.

**Pull request merged**
