### PR TITLE
QA Stencil

### PR DESCRIPTION
**Pull request by vv-monsalve**
This PR includes the latest source, production, and font files for the Inline family.
The main fixes were:

- Masters and Instance renamed to produce the fonts under the latest Spec.
- New build and production files for the family were created.
- Spacing and kerning fixes based on the job done on Big Shoulders.

After the merge, please review and adjust the following:

Kerning
- [x]  You'd probably want to give it a general review and make some improvements. Keeping the matching number of cases (pairs) would be needed.

Diacritics
- [x] Macron and line below look a bit wide, particularly in Thin masters and for narrow letters.
- [x] Check the position of some anchors, e.g., in /r
- [x] Lcaron. Use the caron alt component
- [x] Caron alt slope and spacing. A more vertical shape is preferred to distinguish it from apostrophe and to avoid the need for extra spacing. See Big Shoulders as a reference.
- [x] Ldot and ldot. The dot loos too close to the base L and separated of the next glyph, particularly for the Catalan use of it
- [x] Check the balance of the bar for hbar, dcroat and tbar.

### CODE REVIEW

**Comment by xotypeco** [comment]
my work on stencil is merged back in now. you'll see different kerning in the Polish, and some fixes where components and paths (in characters containing both) had fallen out of position. these fixes will also need to be made in Big Shoulders, that is my next task.
Screen Shot 2020-08-22 at 11 28 03 AM
Screen Shot 2020-08-22 at 11 28 51 AM

**Comment by vv-monsalve** [comment]
I'm glad to see the improvements. The only thing that concerns me right now is the PR still appears as open, as it hasn't been merged. Are you working on the latest files?

**Comment by xotypeco** [comment]
you'd made this fix, which failed to merge, and I didn't see. just did it.

https://github.com/xotypeco/big_shoulders/pull/24/commits/9cb6d231a312428c5156f010dabaf7a83d4a0b56

everything else is up to date. does this look ok on your end?

**Comment by vv-monsalve** [comment]
That commit was about one of the files to set up the CI cheks, that mentioned on the email. 
It failed at that moment, maybe because of a temporary internet connection issue. Big Shoulders production takes a few minutes given the extent of it, particularly in for Stencil and Inline variants. But you can see it is ok now.

**Pull request merged**
